### ISSUE TITLE
Why only python2

### ISSUE THREAD

**Issue by datatalking** [sartim/MySql-Python-Import-Script#12]
@sartim I liked your code post on MySql converting but why is this only for python 2 but in the README.md you mention python3?

Could you assign me as a contributor and I'll send you a pull request to loop in a feature I've been wanting to build and expand this or are you archiving this code?

**Comment by sartim** [comment]
@datatalking It can work from Python 2.7 - 3.8 most of it tied to [MySQL's official python connector version](https://dev.mysql.com/doc/connector-python/en/connector-python-versions.html). Feel free to contribute in extending the code.
